### ISSUE TITLE
Nested composite definitions are not recognized

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/build-ibmstreams#16]
e.g.:
```
composite MyComposite1(output Out) { ... }
composite MyComposite2(input In; output Out) { ... }
```

**Comment by guychris** [comment]
@queeniema where were you expecting those to be recognized?

**Comment by queeniema** [comment]
In the main composite selector when building...

**Comment by guychris** [comment]
Ah, composites with input or output ports cannot be main composites, so we're correctly hiding them. only an "outer" main composite with no input/output ports can be built.
