### ISSUE TITLE
Start Streaming Analytics service without using the Service Management page

### ISSUE THREAD

**Issue by shusseyIBM** [IBMStreams/build-ibmstreams#27]
For a developer who is working on a Streams application intermittently, the Streaming Analytics service is frequently stopped when coming back to the code in Sublime or VSC. Although it is helpful to be able to navigate to the Service Management page it would improve the experience if service startup could be triggered from the editor rather than having to leave it.
The first option below would be the minimalist approach but also having the second would make the casual coding/learning experience more frictionless.
1. An explicit action the user performs after the build request discovers the service is stopped
2. If the user sets a preference flag, the service is auto started when submitting the build request

**Comment by petenicholls** [comment]
As part of option #1 we would resubmit the build after a successful service start.

**Comment by guychris** [comment]
fixed in v0.4.0, if the Streaming Analytics instance is not running, we prompt to start the instance and build.
