### ISSUE TITLE
Regex for linting build messages breaks when building an application that's not in a namespace

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/build-ibmstreams#31]
**Example**

`HelloWorld.spl:9:33: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: Becon.`

vs.

`Sample/vwap.spl:110:18: CDISP0053E ERROR: An unknown identifier was referenced in the SPL program: csv.`

**Possible Fix**

Adding a `?` quantifier in first capturing group of the regex seems to fix it:

`\/` → `\/?`

`/^([\w.]+\/[\w.]+)\:(\d+)\:(\d+)\:\s+(\w{5}\d{4}[IWE])\s+((ERROR|WARN|INFO)\:.*)$/`

vs.

`/^([\w.]+\/?[\w.]+)\:(\d+)\:(\d+)\:\s+(\w{5}\d{4}[IWE])\s+((ERROR|WARN|INFO)\:.*)$/;`

**Comment by guychris** [comment]
fixed in v0.4.0
