### ISSUE TITLE
Inconsistencies in Command Palette

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/build-ibmstreams#33]
Suggestions:
- Rename `Spl Build` category to `IBM Streams` (to match the context menu category and VS Code behavior)
- Only show commands when user is in the correct context and use the same command labels that are used in the context menu
    - .spl
         - `Build`
         - `Build and submit job`
    - Makefile
        - `Build`
        - `Build and submit job(s)`
    - .sab
        - `Submit job`

![screen shot 2019-01-08 at 9 53 21 am](https://user-images.githubusercontent.com/2454818/50849246-4691ea00-132b-11e9-95a3-23df32fab4ff.png)

**Comment by guychris** [comment]
command palette items were updated in v0.4.0
