### ISSUE TITLE
Building 2 projects at the same time puts sab files in the same folder

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/build-ibmstreams#39]
If I build composite `X` from Project `A` and composite `Y` from Project `B` while the first compilation is still going on, I get `x.sab` and `y.sab` in the output folder for `B`, instead of in their respective folders.

**Comment by guychris** [comment]
Was not able to reproduce this behaviour - if you still see this, please re-open and upload your project directories. Thanks!
