### ISSUE TITLE
Which URL needs to entered for IBM Cloud Private for Data Streams Add-on?

### ISSUE THREAD

**Issue by markheger** [IBMStreams/build-ibmstreams#54]
Streams instance details in Cloud Pak provide several URLs:
externalBuildEndpoint
externalConsoleEndpoint
externalRestEndpoint

It is not mentioned which of them needs to set.
Remark: Ports can differ between BuildEndpoint and ConsoleEndpoint!

**Comment by queeniema** [comment]
@markheger You should enter the URL that's used to access the ICP4D UI. For example, if your UI homepage is https://9.114.60.128:31844/zen/#/homepage, then you should enter `https://9.114.60.128:31844` as the setting value.

**Comment by markheger** [comment]
Thanks
